# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LucidJournal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LucidJournal


  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'


  pod 'react-native-mail', :path => '../node_modules/react-native-mail'



  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'

end

